# NEAT configuration file

[NEAT]
fitness_criterion     = max
fitness_threshold     = 1000
pop_size              = 20
reset_on_extinction   = False

[DefaultGenome]
# Node activation options: 'sigmoid', 'relu', 'tanh', etc.
activation_default      = sigmoid
activation_mutate_rate  = 0.0
activation_options      = sigmoid

# Connection weight options
weight_default          = 0.0
weight_mutate_rate      = 0.9
weight_replace_rate     = 0.1
weight_options          = random

# Node function options
bias_init_mean          = 0.0
bias_init_stdev         = 1.0
bias_max_value          = 30.0
bias_min_value          = -30.0
bias_mutate_power       = 0.5
bias_mutate_rate        = 0.7
bias_replace_rate       = 0.1

# Connection function options
conn_add_prob           = 0.5
conn_delete_prob        = 0.5
enabled_default         = True
feed_forward            = True
initial_connection      = full

# Node mutation options
node_add_prob           = 0.2

# Compatibility options
compatibility_disjoint_coefficient    = 1.0
compatibility_weight_coefficient      = 0.5

num_inputs              = 16
num_outputs             = 24
num_hidden              = 0

# Node deletion probability
node_delete_prob            = 0.3

# Response initialization options
response_init_mean          = 0.0
response_init_stdev         = 1.0

# Response mutation options
response_mutate_rate        = 0.5
response_mutate_power       = 0.5

# Response replacement options
response_replace_rate       = 0.1
response_max_value          = 30.0
response_min_value          = 0.0

# Aggregation mutation options
aggregation_mutate_rate               = 0.5

# Connection weight initialization options
weight_init_mean                      = 0.0
weight_init_stdev                     = 1.0
weight_mutate_power                   = 0.5
weight_max_value                      = 30.0
weight_min_value                      = -30.0

# Connection enabled mutation options
enabled_mutate_rate                   = 0.1

[DefaultSpeciesSet]
compatibility_threshold     = 3.0
# compatibility_threshold_stagnation = 15

[DefaultStagnation]
species_fitness_func        = max
max_stagnation              = 20
species_elitism             = 2

[DefaultReproduction]
elitism                     = 2
survival_threshold          = 0.2
min_species_size            = 2
