name: Check commit state

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python Script
      run: |
        for commit in $(git rev-list --no-merges --count HEAD..HEAD~$GITHUB_EVENT_SIZE); do
          python commit-checker.py $commit
          if [ $? -eq 1 ]; then
            echo "Python script returned 1. Cancelling the push..."
            exit 1
          fi
        done
