name: Clone Repository
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - "Block Push on Norme Failure"
    types:
      - completed
env:
  MIRROR_URL:
    git@github.com:EpitechPromo2026/B-YEP-400-REN-4-1-zappy-mael1.becel.git

jobs:
  cleaning:
    name: Cleaning...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  compilation:
    name: Compiling...
    needs: cleaning
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo make

  mirroring:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
          echo make
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}