name: Block Push on Norme Failure

on:
  push:
    branches-ignore:
      - ga-ignore-**

jobs:
  check_norme:
    runs-on: ubuntu-latest

    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: check.sh $(pwd) $(pwd)
      - run: |
          FILENAME=coding-style-reports.log
          ERRORS=0
          if [ -s "${FILENAME}" ]; then
            while IFS=$'\n'; read line
            do
              TEMP=$(echo $line)
              FILE=$(echo $TEMP | cut -d : -f 1)
              LINE=$(echo $TEMP | cut -d : -f 2)
              TITLE=$(echo $TEMP | cut -d : -f 3)
              TITLE="$TITLE coding style error"
              ELEMENT=$(echo $TEMP | cut -d : -f 4)
              ERRORS=$((ERRORS+1))
              echo "::error file=$FILE,line=$LINE,title=$TITLE::$ELEMENT"
            done < "${FILENAME}"
          fi
          if [ $ERRORS -gt 0 ]; then
            exit 1
          fi
