name: Block Push on Norme Failure

on:
  push:
    branches-ignore:
      - ga-ignore-**

jobs:
  check_norme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download norme.sh script
        run: |
          curl -o norme.sh https://raw.githubusercontent.com/maelbecel/Usefull-scripts/main/norme/norme.sh
          chmod +x norme.sh

      - name: Run norme.sh script
        run: |
          ./norme.sh -v .
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "The norme.sh script failed. Push has been blocked."
            exit 1
          fi
