name: Run Test Script on Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  run_test_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test script
        run: ./path/to/test-script.sh
        continue-on-error: true

      - name: Check script exit code
        id: check_exit_code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "The test script failed. Push has been blocked."
            exit 1
          fi
